// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeluqueriaCanina.Data;

#nullable disable

namespace PeluqueriaCanina.Migrations
{
    [DbContext(typeof(ContextoAcqua))]
    [Migration("20251125202007_valoration")]
    partial class valoration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDeAdministrador.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duracion")
                        .HasColumnType("time");

                    b.Property<string>("NombreDelServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDeCliente.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDeCliente.Valoracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaValoracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeluqueroId")
                        .HasColumnType("int");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("int");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PeluqueroId");

                    b.HasIndex("TurnoId")
                        .IsUnique();

                    b.ToTable("Valoraciones");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDePago.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroTransaccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProcesadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.Property<string>("Ultimos4Digitos")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("TurnoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDePeluquero.Jornada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraDeFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraDeInicio")
                        .HasColumnType("time");

                    b.Property<int>("PeluqueroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeluqueroId");

                    b.ToTable("Jornadas");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDeTurno.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duracion")
                        .HasColumnType("time");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueValorado")
                        .HasColumnType("bit");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<int?>("PeluqueroId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId");

                    b.HasIndex("PeluqueroId");

                    b.HasIndex("ServicioId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.REPORTES.ReporteDetallePeluqueroView", b =>
                {
                    b.Property<int>("Cancelados")
                        .HasColumnType("int");

                    b.Property<string>("NombrePeluquero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Realizados")
                        .HasColumnType("int");

                    b.Property<decimal>("Recaudado")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("vw_ReporteDetallePeluquero", (string)null);
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.REPORTES.ReportePeluquerosPorServicio", b =>
                {
                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("NombrePeluquero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_ReportePeluquerosPorServicio", (string)null);
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.REPORTES.ReporteServiciosTotales", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ReporteServiciosTotales", (string)null);
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.Users.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContraseñaHasheada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator().HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.Users.Administrador", b =>
                {
                    b.HasBaseType("PeluqueriaCanina.Models.Users.Persona");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.Users.Cliente", b =>
                {
                    b.HasBaseType("PeluqueriaCanina.Models.Users.Persona");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.Users.Peluquero", b =>
                {
                    b.HasBaseType("PeluqueriaCanina.Models.Users.Persona");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Peluquero");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDeCliente.Mascota", b =>
                {
                    b.HasOne("PeluqueriaCanina.Models.Users.Cliente", "Cliente")
                        .WithMany("Mascotas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDeCliente.Valoracion", b =>
                {
                    b.HasOne("PeluqueriaCanina.Models.Users.Cliente", "Cliente")
                        .WithMany("Valoraciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeluqueriaCanina.Models.Users.Peluquero", "Peluquero")
                        .WithMany("Valoraciones")
                        .HasForeignKey("PeluqueroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeluqueriaCanina.Models.ClasesDeTurno.Turno", "Turno")
                        .WithOne("Valoracion")
                        .HasForeignKey("PeluqueriaCanina.Models.ClasesDeCliente.Valoracion", "TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Peluquero");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDePago.Pago", b =>
                {
                    b.HasOne("PeluqueriaCanina.Models.ClasesDeTurno.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDePeluquero.Jornada", b =>
                {
                    b.HasOne("PeluqueriaCanina.Models.Users.Peluquero", "Peluquero")
                        .WithMany("Jornadas")
                        .HasForeignKey("PeluqueroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peluquero");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDeTurno.Turno", b =>
                {
                    b.HasOne("PeluqueriaCanina.Models.ClasesDeCliente.Mascota", "Mascota")
                        .WithMany("Turnos")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeluqueriaCanina.Models.Users.Peluquero", "Peluquero")
                        .WithMany("Turnos")
                        .HasForeignKey("PeluqueroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeluqueriaCanina.Models.ClasesDeAdministrador.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mascota");

                    b.Navigation("Peluquero");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDeCliente.Mascota", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.ClasesDeTurno.Turno", b =>
                {
                    b.Navigation("Valoracion");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.Users.Cliente", b =>
                {
                    b.Navigation("Mascotas");

                    b.Navigation("Valoraciones");
                });

            modelBuilder.Entity("PeluqueriaCanina.Models.Users.Peluquero", b =>
                {
                    b.Navigation("Jornadas");

                    b.Navigation("Turnos");

                    b.Navigation("Valoraciones");
                });
#pragma warning restore 612, 618
        }
    }
}
